name: Generate Keystore

on:
  workflow_dispatch:
    inputs:
      keystore_password:
        description: "Keystore password"
        required: true
      key_alias:
        description: "Key alias"
        required: true
        default: "asteri"
      key_password:
        description: "Key password"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Generate keystore
        env:
          KEYSTORE_PASSWORD: ${{ inputs.keystore_password }}
          KEY_ALIAS: ${{ inputs.key_alias }}
          KEY_PASSWORD: ${{ inputs.key_password }}
        run: |
          echo "::add-mask::$KEYSTORE_PASSWORD"
          echo "::add-mask::$KEY_ALIAS"
          echo "::add-mask::$KEY_PASSWORD"
          keytool -genkeypair -v \
            -keystore asteri.keystore \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -alias "$KEY_ALIAS" \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Asteri, OU=Dev, O=Asteri, L=Kyiv, S=Kyiv, C=UA"
          base64 asteri.keystore > asteri.keystore.b64

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: asteri-keystore
          path: |
            asteri.keystore
            asteri.keystore.b64
